apiVersion: v2
name: et-msg-handler
home: https://github.com/hmcts/et-msg-handler
version: 0.0.38
description: HMCTS Employment Tribunals Message Handler service
maintainers:
  - name: HMCTS Employment Tribunals Team
dependencies:
  - name: java
    version: 5.3.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
  - name: servicebus
    version: 1.0.7
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
    condition: servicebus.enabled
