java:
  image: 'hmctspublic.azurecr.io/et/et-msg-handler:latest'
  applicationPort: 8085
  ingressHost: et-msg-handler-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: et
  keyVaults:
    et-msg-handler:
      secrets:
        - msg-handler-POSTGRES-HOST
        - msg-handler-POSTGRES-PORT
        - msg-handler-POSTGRES-DATABASE
        - msg-handler-POSTGRES-USER
        - msg-handler-POSTGRES-PASS
        - caseworker-user-name
        - caseworker-password
        - gov-notify-api-key
        - et-msg-handler-s2s-secret
    et:
      secrets:
        - create-updates-queue-send-connection-string
        - create-updates-queue-listen-connection-string
        - update-case-queue-send-connection-string
        - update-case-queue-listen-connection-string
        - AppInsightsInstrumentationKey
        - idam-secret
  environment:
    REFORM_TEAM: et
    REFORM_SERVICE_NAME: et-msg-handler
    REFORM_SERVICE_TYPE: java
    REFORM_ENVIRONMENT: preview
    ROOT_LOGGING_LEVEL: INFO
    LOG_OUTPUT: single
    ET_MSG_HANDLER_URL: "http://et-msg-handler-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    IDAM_API_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    IDAM_API_JWK_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net/jwks"
    IDAM_API_OIDC_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net/o/token"
    IDAM_CLIENT_REDIRECT_URL: "https://et-msg-handler-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/oauth2redirect"
    SERVICE_AUTH_PROVIDER_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    CCD_DATA_STORE_API_URL: "http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    MICRO_SERVICE: "et_msg_handler"
    ET_MSG_HANDLER_DB_CONN_OPTIONS: ?sslmode=require
