java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    ET_MSG_HANDLER_POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    ET_MSG_HANDLER_POSTGRES_DATABASE: "{{ .Values.postgresql.postgresqlDatabase}}"
    ET_MSG_HANDLER_POSTGRES_USER: "{{ .Values.postgresql.postgresqlUsername}}"
    ET_MSG_HANDLER_POSTGRES_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    ET_MSG_HANDLER_DB_CONN_OPTIONS: ""
  keyVaults:
    et-msg-handler:
      secrets:
        - name: caseworker-user-name
          alias: CASEWORKER_USER_NAME
        - name: caseworker-password
          alias: CASEWORKER_PASSWORD
        - name: gov-notify-api-key
          alias: GOV_NOTIFY_API_KEY
        - name: et-msg-handler-s2s-secret
          alias: ET_MSG_HANDLER_S2S_SECRET
        - name: idam-client-secret
          alias: IDAM_CLIENT_SECRET
    et:
      secrets:
        - name: create-updates-queue-send-connection-string
          alias: CREATE_UPDATES_QUEUE_SEND_CONNECTION_STRING
        - name: create-updates-queue-listen-connection-string
          alias: CREATE_UPDATES_QUEUE_LISTEN_CONNECTION_STRING
        - name: update-case-queue-send-connection-string
          alias: UPDATE_CASE_QUEUE_SEND_CONNECTION_STRING
        - name: update-case-queue-listen-connection-string
          alias: UPDATE_CASE_QUEUE_LISTEN_CONNECTION_STRING
  postgresql:
    enabled: true

